
(define default-im-name 'byeoru)
(define enabled-im-list '(byeoru))
(define byeoru-layout 'byeoru-layout-strict3final)

;; (define byeoru-jamo-orderedness 'ordered)
;; (define byeoru-esc-turns-off? #t)
;; (define byeoru-commit-by-word? #f)
;; (define byeoru-shifted-romaja-isolates-vowel? #f)
;; (define byeoru-nr-candidate-max 10)
;; (define byeoru-symbol-cache-size 5)
;; (define byeoru-conversion-history-size 1000)
;; (define byeoru-conversion-history-path "/home/jj/.uim.d/byeoru/byeoru-history")
;; (define byeoru-personal-dict-path "/home/jj/.uim.d/byeoru/byeoru-dict")
;; (define byeoru-sys-dict-path "/nix/store/ccsjmq9l451fdbqndqf275vc84cgwkkh-uim-1.8.8/share/uim/byeoru-data/byeoru-dict")
;; (define byeoru-refresh-xkb-map-at-switch-on? #t)
;; (define byeoru-compatibility-jamos-for-incomplete-syllables? #t)
