# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  hardware.enableRedistributableFirmware = lib.mkDefault true;
  hardware.firmware = with pkgs; [ rtw89-firmware ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ehci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "amdgpu" "kvm-amd" "rtw89core" "k10temp" "zenpower" ];
  boot.extraModulePackages = [ pkgs.linuxPackages_latest.rtw89 ];
  boot.hardwareScan = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/67a0bac5-60ab-415a-aa61-c9994b57d142";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A48-F9D3";
      fsType = "vfat";
    };

  swapDevices = [];
}
